version: "3.9"
services:
  postgres-tapestry:
    container_name: postgres-tapestry
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=tapestrydb
    ports:
      - "5432:5432"